#!/bin/bash

#CREAR UN DIRECTORIO SIMPLE
mkdir directorio

#CREAR DIRECTORIOS INTERMEDIOS SI NO EXISTEN
mkdir -p directorio/subdirectorio

#CREAR DIRECTORIO ESPECIFICANDO SUS PERMISOS
mkdir -m 755 directorio

#CREAR UN DIRECTORIO TEMPORAL
mkdir -t /tmp/directorioTemporal

#CREAR DIRECTORIO CON PREGUNTA PARA SOBREESCRIBIR
mkdir -i directorio

#CREAR DIRECTORIO QUE AVISE SI YA EXISTE
mkdir -p directorio